In [1]:
import numpy as np

In [2]:
# np.loadtxt('file.txt') | From a text file
# np.genfromtxt('file.csv',delimiter=',') | From a CSV file
# np.savetxt('file.txt',arr,delimiter=' ') | Writes to a text file
# np.savetxt('file.csv',arr,delimiter=',') 

In [8]:
temp=np.genfromtxt("us_temp.csv",delimiter=',')

In [9]:
temp

array([[nan, nan, nan, nan, nan, nan],
       [nan, 52., 31., 38., 57., 43.],
       [nan, 57., 33., 42., 60., 47.],
       [nan, 65., 42., 50., 62., 56.],
       [nan, 73., 55., 61., 63., 67.],
       [nan, 80., 67., 71., 64., 75.],
       [nan, 86., 75., 79., 66., 84.],
       [nan, 89., 80., 84., 67., 88.],
       [nan, 88., 78., 83., 68., 87.],
       [nan, 82., 71., 75., 70., 80.],
       [nan, 73., 59., 64., 69., 68.],
       [nan, 64., 48., 54., 63., 58.],
       [nan, 54., 36., 43., 57., 47.]])

In [10]:
import pandas as pd

In [11]:
temp=pd.read_csv('us_temp.csv')

In [12]:
temp

months_name  Atlanta  Buffalo  New York City  San Francisco  Washington
0      January       52       31             38             57          43
1     February       57       33             42             60          47
2        March       65       42             50             62          56
3        April       73       55             61             63          67
4          May       80       67             71             64          75
5         June       86       75             79             66          84
6         July       89       80             84             67          88
7       August       88       78             83             68          87
8    September       82       71             75             70          80
9      October       73       59             64             69          68
10    November       64       48             54             63          58
11    December       54       36             43             57          47

In [15]:
pd.melt(temp,id_vars='months_name',var_name='city',value_name='temp')

months_name           city  temp
0      January        Atlanta    52
1     February        Atlanta    57
2        March        Atlanta    65
3        April        Atlanta    73
4          May        Atlanta    80
5         June        Atlanta    86
6         July        Atlanta    89
7       August        Atlanta    88
8    September        Atlanta    82
9      October        Atlanta    73
10    November        Atlanta    64
11    December        Atlanta    54
12     January        Buffalo    31
13    February        Buffalo    33
14       March        Buffalo    42
15       April        Buffalo    55
16         May        Buffalo    67
17        June        Buffalo    75
18        July        Buffalo    80
19      August        Buffalo    78
20   September        Buffalo    71
21     October        Buffalo    59
22    November        Buffalo    48
23    December        Buffalo    36
24     January  New York City    38
25    February  New York City    42
26       March  New York City    50
27       April  New York City    61
28         May  New York City    71
29        June  New York City    79
30        July  New York City    84
31      August  New York City    83
32   September  New York City    75
33     October  New York City    64
34    November  New York City    54
35    December  New York City    43
36     January  San Francisco    57
37    February  San Francisco    60
38       March  San Francisco    62
39       April  San Francisco    63
40         May  San Francisco    64
41        June  San Francisco    66
42        July  San Francisco    67
43      August  San Francisco    68
44   September  San Francisco    70
45     October  San Francisco    69
46    November  San Francisco    63
47    December  San Francisco    57
48     January     Washington    43
49    February     Washington    47
50       March     Washington    56
51       April     Washington    67
52         May     Washington    75
53        June     Washington    84
54        July     Washington    88
55      August     Washington    87
56   September     Washington    80
57     October     Washington    68
58    November     Washington    58
59    December     Washington    47

In [16]:
temp

months_name  Atlanta  Buffalo  New York City  San Francisco  Washington
0      January       52       31             38             57          43
1     February       57       33             42             60          47
2        March       65       42             50             62          56
3        April       73       55             61             63          67
4          May       80       67             71             64          75
5         June       86       75             79             66          84
6         July       89       80             84             67          88
7       August       88       78             83             68          87
8    September       82       71             75             70          80
9      October       73       59             64             69          68
10    November       64       48             54             63          58
11    December       54       36             43             57          47

In [22]:
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [23]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [27]:
np.random.rand(5,6)

array([[0.4996776 , 0.91137791, 0.09534182, 0.5418415 , 0.79692088,
        0.5821215 ],
       [0.87239053, 0.51973966, 0.26828929, 0.10014974, 0.51499521,
        0.94465332],
       [0.20628981, 0.31587278, 0.23537983, 0.36190295, 0.85481642,
        0.55674795],
       [0.34575618, 0.82064141, 0.19963214, 0.82328642, 0.1723064 ,
        0.18593769],
       [0.55191233, 0.19565474, 0.02727807, 0.13171549, 0.29876461,
        0.66932147]])

In [40]:
np.random.randint(10,120,size=(2,3))

array([[ 33, 109, 103],
       [ 21,  13,  96]])

In [43]:
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x000001F79DFFD040>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +

In [46]:
arr=np.array([1,2,3,4,5,6,7,8,9,0])

In [49]:
a=np.copy(arr)

In [56]:
a.view()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [63]:
a.sort(axis=0)

In [64]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
ar=np.arange(10,2)

In [130]:
twod=np.random.randint(5,size=(2,3))


In [78]:
twod.flatten()

array([1, 3, 0, 2, 4, 2])

In [131]:
twod.resize((5,6))

In [133]:
arr2=twod

In [108]:
a=np.insert(twod,2,10)

In [138]:
arr2


array([[3, 0, 0, 3, 3, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [102]:
np.abs(a)

array([ 4,  1, 10,  1,  4,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [113]:
arr1=np.array([1.2,-3,4])

In [114]:
arr1

array([ 1.2, -3. ,  4. ])

In [115]:
np.abs(arr1)

array([1.2, 3. , 4. ])

In [139]:
np.split(arr2,5)

[array([[3, 0, 0, 3, 3, 4]]),
 array([[0, 0, 0, 0, 0, 0]]),
 array([[0, 0, 0, 0, 0, 0]]),
 array([[0, 0, 0, 0, 0, 0]]),
 array([[0, 0, 0, 0, 0, 0]])]

In [136]:
np.hsplit(arr2,6)

[array([[3],
        [0],
        [0],
        [0],
        [0]]),
 array([[0],
        [0],
        [0],
        [0],
        [0]]),
 array([[0],
        [0],
        [0],
        [0],
        [0]]),
 array([[3],
        [0],
        [0],
        [0],
        [0]]),
 array([[3],
        [0],
        [0],
        [0],
        [0]]),
 array([[4],
        [0],
        [0],
        [0],
        [0]])]

In [145]:
a1=np.random.rand(3,1)

In [156]:
a2=np.random.rand(1,6)

In [157]:
a1*a2

array([[0.01532592, 0.03398785, 0.20837539, 0.09260066, 0.17770964,
        0.01265738],
       [0.05593456, 0.12404448, 0.76050167, 0.33796199, 0.64858178,
        0.04619526],
       [0.05726217, 0.12698869, 0.77855227, 0.34598356, 0.66397594,
        0.04729171]])

In [158]:
x = np.linspace(0, 10, 100)

In [159]:
x

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96